-- 清理数据库脚本
TRUNCATE TABLE "GroupMessage" CASCADE;
TRUNCATE TABLE "Chat" CASCADE;
TRUNCATE TABLE "GroupMember" CASCADE;
TRUNCATE TABLE "Group" CASCADE;
TRUNCATE TABLE "Notification" CASCADE;
TRUNCATE TABLE "Vote" CASCADE;
TRUNCATE TABLE "Comment" CASCADE;
TRUNCATE TABLE "Post" CASCADE;
TRUNCATE TABLE "Follow" CASCADE;
TRUNCATE TABLE "User" CASCADE;